### ISSUE TITLE
编译报错，请帮忙看看

### ISSUE THREAD

**Issue by almighty1982** [iHaPBoy/vue-zhihudaily#5]
在vue2.0的环境编译，会报错

E:\CODE\vue\vue_test\vue-zhihudaily-2>npm install
npm WARN tar ENOENT: no such file or directory, open 'E:\CODE\vue\vue_test\vue-z
hihudaily-2\node_modules\.staging\acorn-dynamic-import-9c6fd649\src\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\CODE\vue\vue_test\vue-z
hihudaily-2\node_modules\.staging\buffer-xor-09ce2603\test\index.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\CODE\vue\vue_test\vue-z
hihudaily-2\node_modules\.staging\acorn-281b486f\dist\acorn.es.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\CODE\vue\vue_test\vue-z
hihudaily-2\node_modules\.staging\acorn-dynamic-import-9c6fd649\src\inject.js'
npm WARN tar ENOENT: no such file or directory, open 'E:\CODE\vue\vue_test\vue-z
hihudaily-2\node_modules\.staging\buffer-xor-09ce2603\test\fixtures.json'
**npm ERR! code E404**
**npm ERR! 404 Not Found: @types/node@6.0.85**

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\z00287825\AppData\Roaming\npm-cache\_logs\2018-01-03T09_52
_44_060Z-debug.log

**Comment by iHaPBoy** [comment]
请尝试升级 Node 版本到 8.x
